[package]
name = "kate-proof"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.41"
dusk-plonk = { git = "https://github.com/maticnetwork/plonk.git", branch = "v0.8.2-polygon-5" }
dusk-bytes = { version = "0.1.5" }
rand = "0.8.4"
rand_chacha = "0.3"
merlin = {version = "3.0"}
